services:
  app:
    container_name: yummypass-container
    image: chamingyeong/yummypass:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SERVER_ACCESS_KEY=${SERVER_ACCESS_KEY}
      - SERVER_SECRET_KEY=${SERVER_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
